### ISSUE TITLE
Odd != Prime

### ISSUE THREAD

**Issue by BlackCapCoder** [olaven/jsbiblio#4]
https://github.com/olaven/jsbiblio/blob/5e77363680f2b440340289f23604ed17497eadac/jsBiblio.js#L157

Checking whether a number is odd is not a valid way to check for primality. A simple but slow way to check for primality is:
```javascript
function isPrime (n) {
  if (n%2==0 || n%3==0) return n==2||n==3;
  if (n < 5) return false;

  // All primes >3 satisfies x*6 +- 1
  for (let i = 5; i <= Math.ceil(Math.sqrt(n)); i+=6)
    if (n%i == 0 || n%(i+2) == 0) return false;

  return true;
} // You could also just check for non-divisability with all numbers [2..n-1]

```

However, despite the fact that problems related to primes are generally, [most likely in NP](https://www.youtube.com/watch?v=YX40hbAHx3s). This particular problem of checking for primality can be solved fairly quickly [probabilistically](https://en.wikipedia.org/wiki/Miller%E2%80%93Rabin_primality_test).

**Comment by olaven** [comment]
Ooops, what an embarrassing mistake! I will fix this at once. Thanks a lot, @BlackCapCoder!

**Comment by BlackCapCoder** [comment]
Just a friendly heads up that your fix is 16 times slower than the function I wrote above.

Both functions were tested with:
```javascript
// Test the first 10 million numbers for primality
for (let i = 0; i < 10000000; i++) isPrime(i);
```

```bash
$ time node isPrime1.js
node isPrime1.js  4.04s user 0.02s system 99% cpu 4.095 total
# 4 seconds

$ time node isPrime2.js
node isPrime2.js  63.74s user 0.03s system 99% cpu 1:03.85 total
# 63.7 seconds
```
